
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS role text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS semester text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS batch text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS subjects text[] DEFAULT NULL,
ADD COLUMN IF NOT EXISTS onboarding_completed boolean NOT NULL DEFAULT false;
